swagger: '2.0'
info:
  title: Boox API
  version: '1.0'
paths:
  /documents:
    get:
      summary: Get all documents
      parameters:
        - in: path
          type: integer
          required: true
          name: search
          description: Numeric ID
      produces:
        - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              data:
                type: array
              totalPages:
                type: number
            required:
              - data
              - totalPages
    post:
      produces:
        - application/json;charset=utf-8
      responses:
        '200':
          description: ''
          schema:
            type: object
definitions:
  Document:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      author:
        type: string
      annotations:
        type: array
        items:
          $ref: '#/definitions/Annotation'
  Annotation:
    type: object
    properties:
      id:
        type: integer

